name: 'Multiple Artifacts Downloader'
description: ''
author: 'hawkeye116477'

# Define your inputs here.
inputs:
  repo-token:
    description: 'The GITHUB_TOKEN secret'
    default: '${{ github.token }}'
  names:
    description: "Artifact names"
    required: true
  path:
    description: 'Destination path'
    required: true

runs:
  using: node20
  main: dist/index.js
